apps/api/__init__.py
from flask import Blueprint, jsonify

from config import settings
from utils.file import Posts

from loguru import logger

logger.add(f'{settings.APP_DIR}/api.log', format='{time} {level} {message}', level='INFO')

api = Blueprint('api', __name__)

posts_all = Posts(f'{settings.APP_DIR}/data/posts.json')


@api.route('/posts')
def posts_all_page():
    posts = posts_all.get_all()
    logger.info('Запрос /api/posts')
    return jsonify(posts)


@api.route('/posts/<int:pk>')
def post_pk_page(pk):
    post = posts_all.get_by_pk(pk)
    logger.info(f'Запрос /api/posts/{pk}')
    return jsonify(post)

apps/main/__init__.py
from flask import Flask

from apps.posts.views import bp_posts
from apps.search.views import bp_search
from apps.users.views import bp_users


from apps.api import api

from config import settings


app = Flask(__name__,
            template_folder=f'{settings.APP_DIR}/templates',
            static_folder=f'{settings.APP_DIR}/static'
            )


app.config.from_object(settings.DevelopmentConfig)
app.register_blueprint(bp_posts)
app.register_blueprint(bp_search)
app.register_blueprint(bp_users)
app.register_blueprint(api, url_prefix='/api')



@app.errorhandler(404)
def error_page(error):
    return f'{error}', 404

@app.errorhandler(500)
def error_page(error):
    return f'{error}', 500

apps/posts/views.py
from flask import Blueprint, render_template, abort

from config import settings
from utils.file import Posts, Comments

bp_posts = Blueprint('bp_posts', __name__)

posts_all = Posts(f'{settings.APP_DIR}/data/posts.json')
comments_all = Comments(f'{settings.APP_DIR}/data/comments.json')

@bp_posts.route('/')
def index_page():
   posts = posts_all.get_all()
   return render_template('posts/index.html', posts_all=posts)


@bp_posts.route('/posts/<int:pk>')
def post_pk(pk):
   comments = comments_all.get_comments_by_id(pk)
   try:
      post = posts_all.get_by_pk(pk)
      return render_template('posts/post.html', post=post[0], comments=comments)
   except IndexError:
      abort(404)

apps/search/views.py
from flask import Blueprint, request,  render_template,  redirect, url_for


from config import settings
from utils.file import Posts

bp_search = Blueprint('bp_search', __name__)

posts_all = Posts(f'{settings.APP_DIR}/data/posts.json')

@bp_search.route('/search/')
def search_page():
    s = request.args.get('s')
    search = posts_all.get_search(s)
    if not s or not search:
        return redirect(url_for('bp_posts.index_page'))
    else:
        return render_template('search/search.html', s=s, search=search)

apps/users/views.py
from flask import Blueprint, render_template, redirect, url_for, abort

from config import settings
from utils.file import Posts

bp_users = Blueprint('bp_users', __name__)

users_all = Posts(f'{settings.APP_DIR}/data/posts.json')


@bp_users.route('/users/<string:username>')
def user_name_page(username):
    user = users_all.get_by_user(username)
    if not user:
        abort(404)
    else:
        return render_template('users/user-feed.html', user_posts=user)


@bp_users.errorhandler(404)
def error_page(error):
    return f'{error}', 404

@bp_users.errorhandler(500)
def error_page(error):
    return f'{error}', 500

templates/posts/index.html
{% extends 'base_.html' %}

{% block content %}
    <section class="items">
      {% if posts_all %}
        {% for post in posts_all %}
            <div class="items__item item">
        <div class="item__top">
          <a href="{{ url_for('bp_users.user_name_page',username=post.poster_name) }}" class="item__head">
            <div class="item__ava-wrap">
              <img src="{{ post.poster_avatar }}" alt="" class="item__ava" width="47">
            </div>
            <span class="item__username">{{ post.poster_name }}</span>
          </a>
        </div>
        <a href="{{ url_for('bp_posts.post_pk', pk=post.pk) }}" class="item__post-link">
          <img src="{{ post.pic }}" alt="" width="348" class="item__post-img">
        </a>
        <p class="item__descr">{{ post.content|truncate(50) }}</p>
        <div class="item__post-info">
          <div class="item__counter">
            <img src="{{ url_for('static', filename='img/eye.png') }}" alt="" class="item__counter-icon" width="26">
            <span class="item__counter-text">212</span>
          </div>
        </div>
        <div class="item__post-bottom">
          <a href="{{ url_for('bp_posts.post_pk', pk=post.pk) }}" class="item__btn-more">Подробнее</a>
          <button type="button" class="item__bookmark-btn">
            <img src="{{ url_for('static', filename='img/bookmark.png') }}" alt="" class="item__bookmark-icon" width="24">
          </button>
        </div>
      </div>
        {% endfor %}
      {% endif %}
      </section>
{% endblock content %}

templates/posts/post.html
{% extends 'base_.html' %}

{% block content %}

    <section class="items">
      <div class="items__item item item--post">
        <div class="item__top">
          <a href="{{ url_for('bp_users.user_name_page',username=post.poster_name) }}" class="item__head">
            <div class="item__ava-wrap">
              <img src="{{ post.poster_avatar }}" alt="" class="item__ava" width="47">
            </div>
            <span class="item__username">{{ post.poster_name }}</span>
          </a>
          <button type="button" class="item__bookmark-btn">
            <img src="{{ url_for('static', filename='img/bookmark.png') }}" alt="" class="item__bookmark-icon" width="24">
          </button>
        </div>
        <a href="" class="item__post-link">
          <img src="{{ post.pic }}" alt="" width="348" class="item__post-img">
        </a>
        <div class="item__descr">
          <p class="item__text">
            {{ post.content }}
          </p>

        </div>
        <div class="item__bottom">
          <div class="item__post-info">
            <p class="item__comments-counter">{{comments|length}} комментария</p>
            <div class="item__counter">
              <img src="{{ url_for('static', filename='img/eye.png') }}" alt="" class="item__counter-icon" width="26">
              <span class="item__counter-text">1023</span>
            </div>
          </div>

          <div class="item__comments">
            {% for comm in comments %}
            <p class="item__comment">
              <b>{{ comm.commenter_name }}:</b> {{ comm.comment }}
            </p>
       {% endfor %}
          </div>

        </div>
      </div>
    </section>

 {% endblock content %}

templates/search/search.html
{% extends 'base_.html' %}

{% block content %}


      <p class="search__results">Найдено постов: {{ search|length }}</p>

    <section class="items">
      {% for post in search %}
      <div class="items__item item">
        <div class="item__top">
          <a href="{{ url_for('bp_users.user_name_page',username=post.poster_name) }}" class="item__head">
            <div class="item__ava-wrap">
              <img src="{{ post.poster_avatar }}" alt="" class="item__ava" width="47">
            </div>
            <span class="item__username">{{ post.poster_name }}</span>
          </a>
        </div>
        <a href="{{ url_for('bp_posts.post_pk', pk=post.pk) }}" class="item__post-link">
          <img src="{{ post.pic }}" alt="" width="348" class="item__post-img">
        </a>
        <p class="item__descr"><a href="/tag.html" class="item__tag">#food</a>{{ post.content }}</p>
        <div class="item__post-info">
          <div class="item__counter">
            <img src="{{ url_for('static', filename='img/eye.png') }}" alt="" class="item__counter-icon" width="26">
            <span class="item__counter-text">{{ post.views_count }}</span>
          </div>
        </div>
        <div class="item__post-bottom">
          <a href="{{ url_for('bp_posts.post_pk', pk=post.pk) }}" class="item__btn-more">Подробнее</a>
          <button type="button" class="item__bookmark-btn">
            <img src="{{ url_for('static', filename='img/bookmark.png') }}" alt="" class="item__bookmark-icon" width="24">
          </button>
        </div>
      </div>
      {% endfor %}
    </section>

  {% endblock content %}

templates/users/user-feed.html
{% extends 'base_.html' %}

{% block content %}

    <section class="items">
      {% for post in user_posts %}
      <div class="items__item item">
        <div class="item__top">
          <a href="{{ url_for('bp_users.user_name_page',username=post.poster_name) }}" class="item__head">
            <div class="item__ava-wrap">
              <img src="{{ post.poster_avatar }}" alt="" class="item__ava" width="47">
            </div>
            <span class="item__username">{{ post.poster_name }}</span>
          </a>
        </div>
        <a href="{{ url_for('bp_posts.post_pk', pk=post.pk) }}" class="item__post-link">
          <img src="img/post5.jpg" alt="" width="348" class="item__post-img">
        </a>
        <p class="item__descr"><a href="#" class="item__tag">#food</a>{{ post.content|truncate(100)  }}</p>
        <div class="item__post-info">
          <div class="item__counter">
            <img src="{{ url_for('static', filename='img/eye.png') }}" alt="" class="item__counter-icon" width="26">
            <span class="item__counter-text">212</span>
          </div>
        </div>
        <div class="item__post-bottom">
          <a href="{{ url_for('bp_posts.post_pk', pk=post.pk) }}" class="item__btn-more">Подробнее</a>
          <button type="button" class="item__bookmark-btn">
            <img src="{{ url_for('static', filename='img/bookmark.png') }}" alt="" class="item__bookmark-icon" width="24">
          </button>
        </div>
      </div>
      {% endfor %}
    </section>



 {% endblock content %}